<a href="https://colab.research.google.com/github/ShreePurvaja/Data-Science-Notes/blob/main/Linear_Regression(Preprocessing_and_Encoding_label).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.DataFrame({
  'Income': [15000, 1800, 120000, 10000],
  'Age': [25, 18, 42, 51],
  'Department': ['HR','Legal','Marketing','Management']
})

df_scaled = df.copy()
col_names = ['Income', 'Age']
features = df_scaled[col_names]
df

Income  Age  Department
0   15000   25          HR
1    1800   18       Legal
2  120000   42   Marketing
3   10000   51  Management

In [3]:
#MinmaxScaler preprocessing method
import sklearn.preprocessing as preprocessing
from sklearn.preprocessing import MinMaxScaler
#x_scaled = (x – x_min)/(x_max – x_min)
scaler = MinMaxScaler(feature_range=(0,1))
df_scaled[col_names] = scaler.fit_transform(features.values)
df_scaled


Income       Age  Department
0  0.111675  0.212121          HR
1  0.000000  0.000000       Legal
2  1.000000  0.727273   Marketing
3  0.069374  1.000000  Management

In [4]:
#Standard Scaler based on standard deviation(individual column and its standard deviation)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled[col_names] = scaler.fit_transform(features.values)
df_scaled


Income       Age  Department
0 -0.449056 -0.685248          HR
1 -0.722214 -1.218219       Legal
2  1.723796  0.609110   Marketing
3 -0.552525  1.294358  Management

In [55]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/USA_Housing.csv")
data


Avg. Area Income  Avg. Area House Age  Avg. Area Number of Rooms  \
0         79545.458574             5.682861                   7.009188   
1         79248.642455             6.002900                   6.730821   
2         61287.067179             5.865890                   8.512727   
3         63345.240046             7.188236                   5.586729   
4         59982.197226             5.040555                   7.839388   
...                ...                  ...                        ...   
4995      60567.944140             7.830362                   6.137356   
4996      78491.275435             6.999135                   6.576763   
4997      63390.686886             7.250591                   4.805081   
4998      68001.331235             5.534388                   7.130144   
4999      65510.581804             5.992305                   6.792336   

      Avg. Area Number of Bedrooms  Area Population         Price  \
0                             4.09     23086.800503  1.059034e+06   
1                             3.09     40173.072174  1.505891e+06   
2                             5.13     36882.159400  1.058988e+06   
3                             3.26     34310.242831  1.260617e+06   
4                             4.23     26354.109472  6.309435e+05   
...                            ...              ...           ...   
4995                          3.46     22837.361035  1.060194e+06   
4996                          4.02     25616.115489  1.482618e+06   
4997                          2.13     33266.145490  1.030730e+06   
4998                          5.44     42625.620156  1.198657e+06   
4999                          4.07     46501.283803  1.298950e+06   

                                                Address  
0     208 Michael Ferry Apt. 674\nLaurabury, NE 3701...  
1     188 Johnson Views Suite 079\nLake Kathleen, CA...  
2     9127 Elizabeth Stravenue\nDanieltown, WI 06482...  
3                             USS Barnett\nFPO AP 44820  
4                            USNS Raymond\nFPO AE 09386  
...                                                 ...  
4995                   USNS Williams\nFPO AP 30153-7653  
4996              PSC 9258, Box 8489\nAPO AA 42991-3352  
4997  4215 Tracy Garden Suite 076\nJoshualand, VA 01...  
4998                          USS Wallace\nFPO AE 73316  
4999  37778 George Ridges Apt. 509\nEast Holly, NV 2...  

[5000 rows x 7 columns]

Splitting the data

In [56]:
x = data[['Avg. Area Income', 'Avg. Area House Age',  'Area Population']]
y = data['Price']
#here split the train dataset(x_train,y_train) and test dataset(x_test,y_test), split 80% data to train dataset and 20% data to test dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)





Preprocessing

In [57]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train) #here scale the  train data and find the min max value for x_train
print(scaler.data_max_)
print(scaler.data_min_)
print(scaler.data_range_)
x_test = scaler.transform(x_test) #here scale the test data  based on x_train min max value to scale the x_test

[1.04702724e+05 9.51908807e+00 6.96217134e+04]
[1.77966312e+04 2.68304290e+00 3.28545054e+03]
[8.69060931e+04 6.83604516e+00 6.63362628e+04]


Scalling

In [23]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)
print('M value:',model.coef_) #m value
print('C value:',model.intercept_) #c value
new = pd.DataFrame({'Avg. Area Income': [79545.458574] , 'Avg. Area House Age': [5.682861],'Area Population': [23086.800503] })
new2 = scaler.transform(new)
print('predicted y value:',model.predict(new2))


M value: [1877076.36416494 1122683.15714992 1008459.61925564]
C value: -906747.9136777618
predicted y value: [1220643.79632083]


Evaluation

In [24]:
from sklearn.metrics import r2_score
print(r2_score(y_test,model.predict(x_test)))

0.7887749166682401


# **Data Collection**

In [94]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/refs/heads/main/insurance.csv")
data

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

# **Split the data**

In [93]:
x=data[['age','sex','smoker','region']]
y=data['charges']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

# **Encoding the label**

In [95]:
# prompt: x=data[['age','sex','smoker']]
# create a lable encoding for the above code

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
x['sex'] = le.fit_transform(x['sex'])
x['region'] = le.fit_transform(x['region'])
x['smoker'] = le.fit_transform(x['smoker'])

print(x.head())


   age  sex  smoker  region
0   19    0       1       3
1   18    1       0       2
2   28    1       0       2
3   33    1       0       1
4   32    1       0       1


<ipython-input-95-9d3b72b93082>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex'] = le.fit_transform(x['sex'])
<ipython-input-95-9d3b72b93082>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['region'] = le.fit_transform(x['region'])
<ipython-input-95-9d3b72b93082>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/u

In [99]:
#prompt : I dont't want 0 in encoding
from sklearn.preprocessing import LabelEncoder

#create a label encoder object
le = LabelEncoder()

#Avoid 0 in encoding by adding 1 to the encoded values
#fit and transform the columns need to be encoded
x['sex_encoded'] = le.fit_transform(x['sex']) + 1
x['region_encoded'] = le.fit_transform(x['region']) + 1
x['smoker_encoded'] = le.fit_transform(x['smoker']) + 1


#drop the original values
x=x.drop(['sex','smoker','region'],axis=1)

#now the columns have numeric values
x


age  sex  smoker  region  sex_encoded  region_encoded  smoker_encoded
0      19    0       1       3            1               4               2
1      18    1       0       2            2               3               1
2      28    1       0       2            2               3               1
3      33    1       0       1            2               2               1
4      32    1       0       1            2               2               1
...   ...  ...     ...     ...          ...             ...             ...
1333   50    1       0       1            2               2               1
1334   18    0       0       0            1               1               1
1335   18    0       0       2            1               3               1
1336   21    0       0       3            1               4               1
1337   61    0       1       1            1               2               2

[1338 rows x 7 columns]

# **Set Features and Target for modified data**

In [100]:
# Select features and target
x = x[['age', 'sex_encoded', 'smoker_encoded', 'region_encoded']]
y = data['charges']

Split data

In [84]:
# 70% train, 30% test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# **Preprocessing and scalling the data**

In [85]:
# Initialize scaler
scaler = MinMaxScaler()

# Fit and transform training data
x_train = scaler.fit_transform(x_train)

# Show min, max, range
print("Max values:", scaler.data_max_)
print("Min values:", scaler.data_min_)
print("Ranges:", scaler.data_range_)

# Transform test data
x_test = scaler.transform(x_test)


Max values: [64.  2.  2.  4.]
Min values: [18.  1.  1.  1.]
Ranges: [46.  1.  1.  3.]


# **Training the model**

In [86]:
model = LinearRegression()
model.fit(x_train, y_train)

print("Model Coefficients:", model.coef_)
print("Model Intercept:", model.intercept_)


Model Coefficients: [ 1.28490792e+04  1.71273654e+02  2.36556923e+04 -2.38256666e-01]
Model Intercept: 2442.0797873509255


# **Testing the model**

In [87]:
# Example new data
new = pd.DataFrame({
    'age': [25],
    'sex_encoded': [2],
    'smoker_encoded': [2],
    'region_encoded': [3]
})

# Scale new input
new_scaled = scaler.transform(new)

# Predict
prediction = model.predict(new_scaled)
print("Predicted Charges:", prediction)


Predicted Charges: [28224.18158689]


# **Model evaluation**

In [88]:
from sklearn.metrics import r2_score
print(r2_score(y_test,model.predict(x_test)))

0.7411161332994894


In [104]:
# prompt: simple gradio app for the above prediction
!pip install gradio
import gradio as gr
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load and preprocess the data (same as your original code)
data=pd.read_csv("https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/refs/heads/main/insurance.csv")
x=data[['age','sex','smoker','region']]
y=data['charges']

le = LabelEncoder()
x['sex_encoded'] = le.fit_transform(x['sex']) + 1
x['region_encoded'] = le.fit_transform(x['region']) + 1
x['smoker_encoded'] = le.fit_transform(x['smoker']) + 1
x=x.drop(['sex','smoker','region'],axis=1)

x = x[['age', 'sex_encoded', 'smoker_encoded', 'region_encoded']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)
scaler = MinMaxScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

model = LinearRegression()
model.fit(x_train, y_train)


def predict_charges(age, sex, smoker, region):
    # Create a DataFrame for input
    input_data = pd.DataFrame({
        'age': [age],
        'sex_encoded': [sex],
        'smoker_encoded': [smoker],
        'region_encoded': [region]
    })

    # Scale the input
    input_scaled = scaler.transform(input_data)

    # Predict
    prediction = model.predict(input_scaled)
    return prediction[0]

iface = gr.Interface(
    fn=predict_charges,
    inputs=[
        gr.Number(label="Age"),
        gr.Radio(choices=[1, 2], label="Sex (1:Female, 2:Male)"), # Assuming 1 and 2 are encoded values
        gr.Radio(choices=[1, 2], label="Smoker (1:No, 2:Yes)"),  # Assuming 1 and 2 are encoded values
        gr.Radio(choices=[1,2,3,4], label="Region (1:NE,2:NW,3:SE,4:SW)")  # Assuming 1,2,3,4 are encoded values
    ],
    outputs=gr.Number(label="Predicted Charges"),
    title="Insurance Charges Prediction",
    description="Predict insurance charges based on age, sex, smoker status and region"
)

iface.launch(share=True)


<ipython-input-104-61a79091c432>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['sex_encoded'] = le.fit_transform(x['sex']) + 1
<ipython-input-104-61a79091c432>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['region_encoded'] = le.fit_transform(x['region']) + 1


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://14478519c8d1bafec8.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
